name: Export Sigma Visual

on:
  workflow_dispatch: {}
  push:
    paths:
      - "app/visuals/**"
      - "scripts/capture_visual.js"
      - ".github/workflows/export-visual.yml"
      - "package.json"
      - "pnpm-lock.yaml"
      - "yarn.lock"

jobs:
  build-and-capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"  # pas de cache => pas besoin de lock file

      - name: Install deps
        run: |
          npm install
          # Sécurité : si puppeteer/wait-on ne sont pas dans le package.json, on les ajoute pour la CI
          npm ls puppeteer >/dev/null 2>&1 || npm i -D puppeteer
          npm ls wait-on  >/dev/null 2>&1 || npm i -D wait-on

      - name: Build
        run: npm run build

      - name: Start Next (background)
        run: |
          npm run start -- -p 3000 &
          npx wait-on http://localhost:3000

      - name: Capture PNG with Puppeteer
        run: node scripts/capture_visual.js
        env:
          CAPTURE_URL: http://localhost:3000/visuals

      - name: Commit image
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs/img/sigma_influence_flow.png"
          message: "chore(visuals): export README visual (Sigma Influence Flow)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
