name: Export Sigma Visual

on:
  workflow_dispatch: {}          # lancement manuel
  push:
    branches: [ main ]           # déclenche à chaque commit sur main

permissions:
  contents: write                # nécessaire pour committer l'image générée

jobs:
  build-and-capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm install
          # Sécurités: installe ces paquets si absents du package.json
          npm ls puppeteer >/dev/null 2>&1 || npm i -D puppeteer
          npm ls wait-on  >/dev/null 2>&1 || npm i -D wait-on

      - name: Build (Vite)
        run: npm run build

      - name: Preview (background, Vite 4173)
        run: |
          npm run start -- --port 4173 &
          npx wait-on http://localhost:4173

      - name: Capture PNG with Puppeteer
        # Si ton script est CommonJS renomme la commande en .cjs
        run: node scripts/capture_visual.js
        env:
          CAPTURE_URL: http://localhost:4173

      - name: Ensure docs/img exists
        run: mkdir -p docs/img

      - name: Commit image (force add if ignored)
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs/img/sigma_influence_flow.png --force"
          message: "chore(visuals): export README visual (Sigma Influence Flow)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
