name: Sigma-Dynamics (Real-Time Analysis)

on:
  schedule:
    - cron: "0 2 * * *"   # Tous les jours à 02:00 UTC
  workflow_dispatch:      # Lancer manuellement depuis l’onglet Actions

permissions:
  contents: read

concurrency:
  group: sigma-dynamics
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg   # Matplotlib hors-écran

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas numpy matplotlib

      # (Optionnel) horodatage pour logs
      - name: Compute output directory (date-based)
        id: date
        run: echo "OUT=artifacts/$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Run Sigma–Dynamics (REAL)
        run: |
          # Le script écrit déjà dans ./outputs/
          python sigma_dynamics.py --steps 200 --fetch-every 50
          echo "Contenu de outputs/"
          ls -lah outputs || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sigma-dynamics-${{ github.run_id }}
          path: |
            outputs/**        # <-- CORRECTION: on uploade le vrai dossier de sortie
          if-no-files-found: error
          retention-days: 14
